version: '3.8'

services:
  user-service:
    build:
      context: .  # Path to the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 of the container to port 5000 on the host
    environment:
      MONGODB_URI: mongodb://mongo:27017/user-service  # MongoDB connection string
      JWT_SECRET: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4YWNlMzkwZDlkNThmYjdkYjUwYjY5MCIsImlhdCI6MTc1NjE2MTY5OSwiZXhwIjoxNzU2MTY1Mjk5fQ.5f_y-CvsHE5YGgyS7yXUOF8PUJYFLDI9ODfsPpaF1EQ  # Replace with your secret
      PORT: 5000
    depends_on:
      - mongo  # Wait for the MongoDB service to start

  mongo:
    image: mongo:latest  # Use the official MongoDB image
    ports:
      - "27017:27017"  # Map port 27017 of the container to port 27017 on the host
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

volumes:
  mongo-data:  # Named volume for MongoDB data persistence